export const PLAYER_LIST_REQUEST = 'PLAYER_LIST_REQUEST'
export const PLAYER_LIST_SUCCESS = 'PLAYER_LIST_SUCCESS'
export const PLAYER_LIST_FAIL = 'PLAYER_LIST_FAIL'

export const PLAYER_DETAILS_REQUEST = 'PLAYER_DETAILS_REQUEST'
export const PLAYER_DETAILS_SUCCESS = 'PLAYER_DETAILS_SUCCESS'
export const PLAYER_DETAILS_FAIL = 'PLAYER_DETAILS_FAIL'